name: 'PR Title Linter'
description: 'Check PR title convention'
inputs:
  token:  # id of input
    description: 'github token'
    required: true
    default: ''
  title-regex:
    description: 'regex for PR title'
    default: '/^(FEATURE|FIX|TASK)\s\|\sISSUE\s\#[1-9]{1,}\s\|\s[\w\s\'\]*$/'
runs:
  using: 'node16'
  main: 'dist/index.js'